export const GET_ALL_ZODIACS = 'GET_ALL_ZODIACS';
export const GET_ALL_ZODIACS_SUCCESS = 'GET_ALL_ZODIACS_SUCCESS ';
export const GET_ALL_ASTRO = 'GET_ALL_ASTRO';
export const GET_ALL_ASTRO_SUCCESS = 'GET_ALL_ASTRO_SUCCESS';
export const GET_REPORTS = 'GET_REPORTS';
export const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
